version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: dockerfile

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
