version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
     - project    
    volumes:
      - ./server:/app/server
  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - project
    volumes:
      - ./client:/app/client
      - /app/client/node_modules 
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - project
networks:
  project:
    driver: bridge
